language: java
services:
  - docker

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk12
  - openjdk13
  - openjdk14

script:
  - mvn package jib:dockerBuild

after_success:
  - bash <(curl -s https://codecov.io/bash)

